CONNECTION_LOOP_INTERVAL = 1
CONNECTION_TIMEOUT = 30
HEARTBEAT_INTERVAL = 10
HEARTBEAT_TIMEOUT_INTERVAL = 2 * HEARTBEAT_INTERVAL
LOGGER_NAME = "thuja"
RECONNECT_INTERVAL = 3
REQUEST_INTERVAL = 0.1
TUYA_PORT = 6668
